##
## EPITECH PROJECT, 2020
## 110borwein
## File description:
## Makefile
##

all:
		@echo -e "\033[3;36m"
		@echo "---------------------------"
		@echo "| WE DONT NEED A MAKEFILE |"
		@echo "| CUS WE DID THIS TASK IN:|"
		@echo "| P Y T H O N ! ! ! ! ! ! |"
		@echo "---------------------------"
		@echo -e "\033[0m"
